Profile view description
teamup-org/mern-template pull request #19
Opened 2024-06-18 19:16 UTC by jhbeeber

Added a script that creates the database and collection in the local MongoDB instance, and also added a script that adds a test user to the new collection. Updated server logic to connect to the local MongoDB instance when the application is running. Updated ReadMe to include instructions for Windows users on how to set up MongoDB on their device. Lastly, added dependencies to support MongoDB.

2024-06-25 02:18 UTC, Steven7zzz commented
The steps for macOS users ti install mongo looks right.

2024-06-25 22:57 UTC, 130008698 commented
The steps for setting up MongoDB on Windows work properly too. The package-lock.json file is currently conflicting with the one in the main branch. Fixing all the conflicts one by one manually doesn't seem like a smart idea though.

2024-06-25 22:58 UTC, 130008698 requested changes
The steps for setting up MongoDB on Windows work properly too. The package-lock.json file is currently conflicting with the one in the main branch. Fixing all the conflicts one by one manually doesn't seem like a smart idea though.

2024-06-29 23:42 UTC, 130008698 approved these changes

2024-06-29 23:59 UTC, merged